name: "CI"
on:
  push:
    branches:
      - '*'
    tags:
      - ''
  pull_request:
    branches:
      - '*'

jobs:
  container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to DockerHub
        if: github.ref == 'refs/heads/master'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Containerfile
          push: ${{ github.ref == 'refs/heads/master' }}
          tags: ${{ secrets.DOCKERHUB_USERNAME || 'aweme-operator' }}/${{ github.event.repository.name }}:latest
